export enum editorTaskActions  {
    OPEN_DIALOG = 'OPEN_DIALOG_FOR_ADD_TASK',
    CLOSE_DIALOG = 'CLOSE_DIALOG_FOR_ADD_TASK',
    CHANGE_START_DATE = 'CHANGE_START_DATE',
    CHANGE_END_DATE = 'CHANGE_END_DATE',
    CHANGE_NAME_TASK = 'CHANGE_NAME_TASK',
    SET_DIALOG_INITIAL_STATE = 'SET_DIALOG_INITIAL_STATE',
}
