export const calendarActions = {
    CHANGE_SELECTED_DATE: 'CALENDAR_CHANGE_SELECTED_DATE',
    CHANGE_MONTH: 'CALENDAR_CHANGE_MONTH',
    CHANGE_YEAR: 'CALENDAR_CHANGE_YEAR',
    CHOOSE_DATE: 'CALENDAR_CHOOSE_DATE',
    SHOW_TODAY: 'SHOW_TODAY',
    CHANGE_DISPLAYED_DATE: 'CHANGE_DISPLAYED_DATE',
    CHANGE_MODE_CALENDAR: 'CHANGE_MODE_CALENDAR',
    GET_LIST_OF_TASKS_FROM_STORAGE: 'GET_LIST_OF_TASKS_FROM_STORAGE',
    ADD_TASK: 'ADD_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    LOCATION_CHANGE: '@@router/LOCATION_CHANGE'
};
